theme: minima
title: Testna web stranica
author: Luka Luketin
description: Malo se igramo s GitHub Pages tematikom da vidimo kako funkcionira i kakva je tematika s web stranicom i static contentom na njoj, je li live itd...
